### ISSUE TITLE
求教，怎么获取up主视频或者内容？

### ISSUE THREAD

**Issue by HaloRyan** [yichengchen/ATV-Bilibili-demo#10]
目前内容列表的功能只有推荐视频，点击查看up主其它视频是刚需， 比search使用频率还高些；
目前在json 只看到owner字段，能否在 推荐位 改为 up主视频list， 或者在推荐下面显示up主所有视频。这样会方便很多 ；

    private func update(with json:JSON) {
        print(json)
        let data = json["data"]
        titleLabel.text = data["title"].stringValue
        upNameLabel.text = data["owner"]["name"].stringValue
        let image = URL(string: data["pic"].stringValue)
            coverImageView.kf.setImage(with: image)
            backgroundImageView.kf.setImage(with: image)

**Comment by yichengchen** [comment]
已添加，点击视频详情页up主按钮
