### ISSUE TITLE
反馈一个投屏直播流稳定crash问题

### ISSUE THREAD

**Issue by uestcwangci** [yichengchen/ATV-Bilibili-demo#102]
错误	00:14:03.375736+0800	itunesstored	tcp_input [C187.1.1.1:3] flags=[R] seq=22499232, ack=0, win=0 state=LAST_ACK rcv_nxt=22499232, snd_una=2546491689
错误	00:14:03.378480+0800	itunesstored	tcp_input [C187.1.1.1:3] flags=[R] seq=22499232, ack=0, win=0 state=CLOSED rcv_nxt=22499232, snd_una=2546491689
错误	00:14:05.557486+0800	wifid	WiFiLQAMgrLinkRecommendationNotify: channel score: chq=4, tx-lat=5, rx-lat=3, tx-loss=5, rx-loss=5, txPer=0.0%, p95-lat=2, RT=0x0, link-recommendation=0x0
错误	00:14:08.191694+0800	ContinuityCaptureAgent	<private> out of session for (null)
错误	00:14:09.130963+0800	wifid	WiFiDeviceSetProperty
错误	00:14:10.573026+0800	wifid	WiFiLQAMgrLinkRecommendationNotify: channel score: chq=4, tx-lat=5, rx-lat=3, tx-loss=5, rx-loss=5, txPer=0.0%, p95-lat=1, RT=0x0, link-recommendation=0x0
错误	00:14:12.709842+0800	BilibiliLive	Setting modalPresentationStyle once <BilibiliLive.VideoPlayerViewController: 0x1429b9200> has been presented will have no effect until it is dismissed and presented again.
错误	00:14:12.720225+0800	BilibiliLive	FBSSceneClientSettings unable to read remoteFocusParentModeEnabled property. Responds to selector: 0. Implements extension: 0. Description: (null)
错误	00:14:12.720401+0800	BilibiliLive	FBSSceneSettings unable to read remoteFocusChildModeEnabled property. Responds to selector: 1. Implements extension: 0. Description: <UIApplicationSceneSettings: 0x302fba5d0> {
    settings = <BSKeyedSettings: 0x3002126a0> {
        displayConfiguration = <FBSDisplayConfiguration: 0x3033d81e0; Main-External; mode: "1920x1080@2x 59.94Hz p3 Dolby">;
        frame = NSRect: {{0, 0}, {1920, 1080}};
        interfaceOrientation = portrait (1);
    };
    subclassSettings = <BSSettings: 0x300c0f0c0> {
        userInterfaceStyle = dark;
        artworkSubtype = 0;
    };
}
错误	00:14:12.720660+0800	BilibiliLive	FBSSceneSettings unable to read remoteFocusChildModeEnabled property. Responds to selector: 1. Implements extension: 0. Description: <UIApplicationSceneSettings: 0x302fba760> {
    settings = <BSKeyedSettings: 0x300213630> {
        displayConfiguration = <FBSDisplayConfiguration: 0x3033d81e0; Main-External; mode: "1920x1080@2x 59.94Hz p3 Dolby">;
        frame = NSRect: {{0, 0}, {1920, 1080}};
        interfaceOrientation = portrait (1);
    };
    subclassSettings = <BSSettings: 0x300c0fe60> {
        userInterfaceStyle = dark;
        artworkSubtype = 0;
    };
}
错误	00:14:12.720824+0800	BilibiliLive	FBSSceneSettings unable to read remoteFocusChildModeEnabled property. Responds to selector: 1. Implements extension: 0. Description: <UIApplicationSceneSettings: 0x302fba7b0> {
    settings = <BSKeyedSettings: 0x300213690> {
        displayConfiguration = <FBSDisplayConfiguration: 0x3033d81e0; Main-External; mode: "1920x1080@2x 59.94Hz p3 Dolby">;
        frame = NSRect: {{0, 0}, {1920, 1080}};
        interfaceOrientation = portrait (1);
    };
    subclassSettings = <BSSettings: 0x300c11ae0> {
        userInterfaceStyle = dark;
        artworkSubtype = 0;
    };
}
错误	00:14:12.721117+0800	BilibiliLive	FBSSceneSettings unable to read remoteFocusChildModeEnabled property. Responds to selector: 1. Implements extension: 0. Description: <UIApplicationSceneSettings: 0x302fba670> {
    settings = <BSKeyedSettings: 0x300212e50> {
        displayConfiguration = <FBSDisplayConfiguration: 0x3033d81e0; Main-External; mode: "1920x1080@2x 59.94Hz p3 Dolby">;
        frame = NSRect: {{0, 0}, {1920, 1080}};
        interfaceOrientation = portrait (1);
    };
    subclassSettings = <BSSettings: 0x300c122e0> {
        userInterfaceStyle = dark;
        artworkSubtype = 0;
    };
}
错误	00:14:12.763533+0800	audiomxd	     CAReportingClient.mm:532   Attempted to remove a reporter not created by this client { careporter_id=57380763080063 }
错误	00:14:12.764266+0800	backboardd	invalidated connection <BSProcessHandle: 0xa9cb62760; BilibiliLive:15341; valid: YES>
错误	00:14:12.855325+0800	runningboardd	RBSStateCapture remove item called for untracked item <RBConnectionClient| 15341 name:app<com.etan.wc.tv.BilibiliLive(516B222B-609D-4CC8-9FBF-6903D84E5AE9)> entitlements:<RBEntitlements| [
			
			]> inheritanceManager:<RBClientInheritanceManager| >>
故障	00:14:12.864401+0800	kernel	trying to get apparently bogus texture handle 0
错误	00:14:12.943864+0800	contextstored	Requested the previousEvent from instantState in setCurrentEvent, but received nil in stream: FocalApp.
错误	00:14:12.976562+0800	symptomsd	Process state is unknown (null)
错误	00:14:14.741964+0800	ReportCrash	Failed to create bundle record for bundleID <private> and error <private>
错误	00:14:15.586637+0800	wifid	WiFiLQAMgrLinkRecommendationNotify: channel score: chq=4, tx-lat=5, rx-lat=3, tx-loss=5, rx-loss=5, txPer=0.0%, p95-lat=1, RT=0x0, link-recommendation=0x0

iPhone投屏直播流能稳定复线，辛苦开发者排查下问题

**Comment by yichengchen** [comment]
原来现在直播也能云视听投屏了

**Comment by uestcwangci** [comment]
看来是个feature了

**Comment by yichengchen** [comment]
fixed
