### ISSUE TITLE
视频投屏显示播放失败

### ISSUE THREAD

**Issue by JimmyYummy** [yichengchen/ATV-Bilibili-demo#105]
显示
```
播放失败
statusFail(code: 1, message: "invalid params")
```

tvOS 17.5.1 [21L580]
build: https://github.com/yichengchen/ATV-Bilibili-demo/actions/runs/9417439072

直播投屏可以正常使用，但是视频投屏不工作

**Comment by yichengchen** [comment]
请更新早早上最新的提交 已修复
