### ISSUE TITLE
更新到tvOS18.2之后build不了了

### ISSUE THREAD

**Issue by mcgradymvp** [yichengchen/ATV-Bilibili-demo#128]
<img width="1789" alt="image" src="https://github.com/user-attachments/assets/5f88e385-50fa-4faa-957a-b81d4a08433c" />
这是什么原因呢

**Comment by mcgradymvp** [comment]
reset到aef4d8e可以用

**Comment by richard-guan-dev** [comment]
https://private-user-images.githubusercontent.com/2382852/395856242-2f9cc390-6add-4f0a-998b-9bf4b086a0ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMjA1NTAsIm5iZiI6MTczNDMyMDI1MCwicGF0aCI6Ii8yMzgyODUyLzM5NTg1NjI0Mi0yZjljYzM5MC02YWRkLTRmMGEtOTk4Yi05YmY0YjA4NmEwZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTZUMDMzNzMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc3OGIyM2Q5NGVmOGQ1NDNiMjVjMDg5MGY5YjM2ZWFlZGY3NGQ4ODgyYTk0MGZhNzNjYzg1ZDQyY2Y3MWU3YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-eKyvkQFESpfcIPmJL1h81AYVW3YEv6Ec8SmVUrg-f4

**Comment by richard-guan-dev** [comment]
![image](https://github.com/user-attachments/assets/3e35b106-190b-4c0b-9263-40996c9c1b8b)
