### ISSUE TITLE
Feeds的LoadMore判断似乎有问题

### ISSUE THREAD

**Issue by RoyLi-Pvt** [yichengchen/ATV-Bilibili-demo#13]
在最后一行没有铺满的情况下不会触发相关事件会导致无法加载
建议将
`indexPath.row == _displayData.count - 1`
修改为
`indexPath.row >= _displayData.count - 2`
提前进行加载
同时在这里判断finished变量似乎也会导致无法正常加载我直接移除这个条件后似乎工作正常
相关代码位置在
[这里](https://github.com/yichengchen/ATV-Bilibili-demo/blob/bae80976e92cd38073713feea4fac307990df795/BilibiliLive/Component/Feed/FeedCollectionViewController.swift#L165)

**Comment by yichengchen** [comment]
在什么页面上会没铺满来着的？印象中现在支持刷新的应该是关注列表和推荐流，应该不大容易拉到底？

**Comment by RoyLi-Pvt** [comment]
就是推荐页面 但是我后来又测试了下和是否铺满最后一行没关系,就是在推荐页面 如果不改上述代码的话很大几率不会触发加载下一页,调试看的话就是焦点移动到最后一行后并没有触发相关事件或者guard条件不符return了,这时候即使重复移开焦点再移动回最后一行也不会触发加载
