### ISSUE TITLE
fetching错误是什么原因？

### ISSUE THREAD

**Issue by yueboviagra** [yichengchen/ATV-Bilibili-demo#14]
![WX20221025-100758@2x](https://user-images.githubusercontent.com/12780545/197665579-8bb5346c-41df-4658-8906-974d4f906823.png)

error project: Error while fetching remote repositoryhttps://github.com/cbpowell/MarqueeLabel: Communication with the service was interrupted.

请问一下，这个错误是什么原因呢

**Comment by yichengchen** [comment]
网络问题哦,可以尝试  file->packages->reset 来重试
