### ISSUE TITLE
真机运行崩溃

### ISSUE THREAD

**Issue by Lhw-Arthas** [yichengchen/ATV-Bilibili-demo#15]
从[#e4667d687c09a2](https://github.com/yichengchen/ATV-Bilibili-demo/commit/e4667d687c09a2da2905aa239ff124a662794127)版本起，我的真机运行构建后的app会直接崩溃

附件是错误日志
tvOS: 15.1.1
Xcode版本: 14.0.1
设备型号: Apple TV 4K (2nd generation)
[crash.txt](https://github.com/yichengchen/ATV-Bilibili-demo/files/9856685/crash.txt)

**Comment by yichengchen** [comment]
啊这。。可能有tvos15的适配问题。16看着是没问题

**Comment by Lhw-Arthas** [comment]
我tvOS16的模拟器也没报错

**Comment by yichengchen** [comment]
related issue https://stackoverflow.com/questions/70213395/self-sizing-collection-view-enters-a-recursive-loop-in-ios-15
