### ISSUE TITLE
[功能建议] 导航栏内容优化、视频详情页背景、非推荐类视频选取

### ISSUE THREAD

**Issue by ayayale** [yichengchen/ATV-Bilibili-demo#18]
感谢团队，从产品角度来说提一些建议，
**顶部导航栏“历史”和“稍后观看”是否可以考虑合并入“我的”？**
原因：1.这两个项目是用户数据的体现，逻辑上属于“我的”；2.历史和稍后观看的使用时长低于导航栏目前现有一个单位的比例（2/6），本属于必要性强但频次低的项目。
**视频背景的高斯模糊是否考虑增加一层半透明暗色背景**
原因：由于部分视频封面较亮，作为背景时文字可读性不强，如果增加一层遮罩压暗，整体质感会有提升。
**缺少推荐以外视频的启动机制**
现象：在没有搜索和分区索引/排行的情况下，脱离其他设备，无法打开推荐内容以外的视频

**Comment by yichengchen** [comment]
updated
