### ISSUE TITLE
xcode在appletv运行时，列表详情都正常，点击播放的时候提示“播放器失败 AVPlayerItemErrorlog：0x282749160”

### ISSUE THREAD

**Issue by codesign2020** [yichengchen/ATV-Bilibili-demo#19]
xcode在appletv运行时，列表详情都正常，点击播放的时候提示“播放器失败 AVPlayerItemErrorlog：0x282749160”

**Comment by yichengchen** [comment]
应该是个别视频？麻烦提供一下视频id

**Comment by codesign2020** [comment]
不是个别视频，好像都这样，只要在详情点播放就报这个错误了
晚会我录个视频您看看
我的盒子是Apple TV HD，系统应该是16.0版本现在

**Comment by yichengchen** [comment]
之前的版本会出现吗？还是最新版本才出现的

**Comment by codesign2020** [comment]
之前版本我还没有装过这个，是最近才试的

**Comment by fanbo0122** [comment]
> 之前的版本会出现吗？还是最新版本才出现的

之前版本没有问题，最新版本才出现的

**Comment by yichengchen** [comment]
> > 之前的版本会出现吗？还是最新版本才出现的
> 
> 之前版本没有问题，最新版本才出现的

尝试一下最新版，在设置里打开hevc优先。同时注意一下画质选择，选低一点看看。atv 4k系列没遇到类似问题
