### ISSUE TITLE
播放失败

### ISSUE THREAD

**Issue by yanjingtui** [yichengchen/ATV-Bilibili-demo#21]
TVos 16
mater分支
点任意一个视频都显示请求失败,decodeFail

**Comment by yichengchen** [comment]
提供视频id 分辨率设置

**Comment by yichengchen** [comment]
麻烦跑一下最新代码，提供一下详细失败弹窗内容

**Comment by fanbo0122** [comment]
> 麻烦跑一下最新代码，提供一下详细失败弹窗内容
请求失败 decodeFail(message;“未能读取数据，因为致据缺失。
valueNotFound(Swift.UnkeyedDecodingContainer,
Swift.DecodingError.Context (codingPath: [CodingKeys(stringValue: I"dash)", intValue: nil), CodingKeys(stringValue: "video|", intValue: nil),
-JSONKey (string Value: |'Index Ol'", intValue: 0), CodingKeys(stringValue: ('"backup_uril", int Value: nil)], debugDescription: | "Cannot get unkeyed decoding container -- found null value instead.|", underlying Error: nil)) ")
