### ISSUE TITLE
【测试反馈】在索尼电视上暂时无法正常识别杜比视界和杜比全景声

### ISSUE THREAD

**Issue by youshandefeiyang** [yichengchen/ATV-Bilibili-demo#23]
不知道这是否依旧是在占了个坑的阶段，手动开启杜比视界和下方无损音频&&杜比全景声，并且开启HEVC，暂时无法正确识别，某Miao可以识别！
![6181598F-06CA-4852-A137-A749364EFBFE](https://user-images.githubusercontent.com/63959400/199412617-85965e46-befb-4c12-9f46-464845cb6cee.jpeg)
![F74DD740-37A2-4DB5-9DA3-ACF77F0406BF](https://user-images.githubusercontent.com/63959400/199412634-b763b65b-8026-4e5d-8177-cff5e607369b.jpeg)

**Comment by youshandefeiyang** [comment]
![009031D2-5182-4415-861D-DB1FE999E1A8](https://user-images.githubusercontent.com/63959400/199412911-1e8ddbe3-f0b0-4d1f-97aa-ec65865acc3e.jpeg)

**Comment by youshandefeiyang** [comment]
无条件支持开源项目

**Comment by Lhw-Arthas** [comment]
你把hevc优先关掉试试，杜比全景声看截图是已点亮(ec-3)

**Comment by yichengchen** [comment]
我这里试验是能点亮debug menu的杜比的，但是因为电视不支持所以不知道有没有效。。。

**Comment by Lhw-Arthas** [comment]
@yichengchen 建议在判断hevc的逻辑中把hvc开头的也加上，因为Dolby Vision 8.4的编码为hvc1.2.4.L150.90，如果只留下hev开头的编码打开hevc开关后会把Dolby Vision 8.4的流过滤掉
```json
{
                "quality": 126,
                "format": "hdflv2",
                "new_description": "杜比视界",
                "display_desc": "杜比视界",
                "superscript": "",
                "codecs": [
                    "hvc1.2.4.L150.90"
                ]
}
```

**Comment by youshandefeiyang** [comment]
> 你把hevc优先关掉试试，杜比全景声看截图是已点亮(ec-3)

那个不是点亮杜比全景声的标志，那是代表外接的是HDMI3口，这个口支持音频回传功能

**Comment by youshandefeiyang** [comment]
> 你把hevc优先关掉试试，杜比全景声看截图是已点亮(ec-3)

实际上，杜比全景声有损数字版也是不支持的
