### ISSUE TITLE
播放失败 XCODE 14.1  TVOS16.1

### ISSUE THREAD

**Issue by gw816** [yichengchen/ATV-Bilibili-demo#25]
XCODE 14.1  TVOS16.1
请求失败,decodeFail(message："未能读取数据，因为数据缺失。
valueNotFound(Swift. UnkeyedDecoding Container,
Swift.DecodingError.Context (coding Path: [CodingKeys(stringValue: \"dash\", intValue: nil), CodingKeys(stringValue: \"dolby\", int Value: nil),
CodingKeys(stringValue: |"audio|", intValue: nil) ], debugDescription: |"Cannot get unkeyed decoding container - - found null value instead.", underlyingError: nil))")

**Comment by yichengchen** [comment]
需要更新到最新哈

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: gw816 ***@***.***>
发送时间: Saturday, November 5, 2022 10:28:20 AM
收件人: yichengchen/ATV-Bilibili-demo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [yichengchen/ATV-Bilibili-demo] 播放失败 XCODE 14.1 TVOS16.1 (Issue #25)


XCODE 14.1 TVOS16.1
请求失败,decodeFail(message："未能读取数据，因为数据缺失。
valueNotFound(Swift. UnkeyedDecoding Container,
Swift.DecodingError.Context (coding Path: [CodingKeys(stringValue: "dash", intValue: nil), CodingKeys(stringValue: "dolby", int Value: nil),
CodingKeys(stringValue: |"audio|", intValue: nil) ], debugDescription: |"Cannot get unkeyed decoding container - - found null value instead.", underlyingError: nil))")

―
