### ISSUE TITLE
播放错误

### ISSUE THREAD

**Issue by W-MS** [yichengchen/ATV-Bilibili-demo#35]
https://bilibili.com/video/BV1sG411M74Y

播放器失败
-16839 "Core MediaErrorDomain” "未能完成操作。
(CoreMediaErrorDomain错
误-16839- Unable to get playlist before long download timer.) " unknownvideo
codecs:
avc1.640032,hev1.1.6.L150.90,avc1.640032,hev1.1.6.L150.90,avc1.640028, audio: mp4a.40.2,mp4a.40.2,mp4a.40.2

**Comment by yichengchen** [comment]
我这边能正常播放，从报错来看可能是bilibili特定cdn抽风了。。。
