### ISSUE TITLE
谢谢开发者。但如何破除7天限制？

### ISSUE THREAD

**Issue by tonnyxiang198** [yichengchen/ATV-Bilibili-demo#36]
我现在会装app,但是只会装7天有效期的。 下面是无限期app安装方法么？但我完全看不懂要怎么做才能破除7天有效期。能否稍微描述详细一点，谢谢！

未签名iPA文件
登录Github账号并在GitHub Action 页面 https://github.com/yichengchen/ATV-Bilibili-demo/actions/workflows/build.yml 寻找最新 run 的底部 Artifacts 下载

**Comment by W-MS** [comment]
不存在无限期的。使用付费的开发证书可以实现多年使用，除此之外只有上架。
https://testflight.apple.com/join/L4JKrE3g TF增加了10个，请尽快兑换

**Comment by tonnyxiang198** [comment]
来迟了 😭

W-MS ***@***.***> 于2022年11月29日周二 13:48写道：
