### ISSUE TITLE
可以支持下暗色背景吗，晚上屏幕白色底有点太亮

### ISSUE THREAD

**Issue by Hotinosin** [yichengchen/ATV-Bilibili-demo#38]
之前尝试自己修改plist 的暗色模式，其他页面都是暗色模式了，但是视频详情页面做了一层封面的底图模糊，去掉之后还是亮色的背景，想问下怎么去除

**Comment by yichengchen** [comment]
底图模糊是小事……各种字体颜色适配才是大问题
