### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by RoyLi-Pvt** [yichengchen/ATV-Bilibili-demo#41]
- 推荐流与客户端不一致，而且会莫名的重复出现一些视频。我这边前段时间是某流量卡的视频现在是极氪拆解视频
- 部分版权内容无法播放了，比如仙王第三季，我是客户端大会员。但是播放会提示404啥都木有可能需要大会员。
- 小电视投屏兼容似乎失效了现在搜索不到设备。

**Comment by W-MS** [comment]
第一个问题也遇到了，某个视频会多次重复

**Comment by yichengchen** [comment]
1- 使用的是iPad端视频流推荐api，重复的基本上广告，没有做过滤
2 fixed
3 和YouTube端口占用冲突，需要退出YouTube客户端才能使用
