### ISSUE TITLE
Memory leak in BMaskProvider

### ISSUE THREAD

**Issue by qsz13** [yichengchen/ATV-Bilibili-demo#43]
Playing this video crashes after a few minutes due to memory leak:
https://www.bilibili.com/video/BV1WG4y1C7mT/

Adding `autoreleasepool` around this while loop seems to mitigate the issue, but I'm not a tvOS developer, so not sure if this is the right fix. Memory usage is still growing, but slow enough to not crash.

https://github.com/yichengchen/ATV-Bilibili-demo/blob/c742445d5f650fe7e2c7bc7638a32a0dfb6cefbf/BilibiliLive/Component/Video/BMaskProvider.swift#L79

**Comment by yichengchen** [comment]
can you help fire a pull request for this ?
