### ISSUE TITLE
可以把视频列表改为每行4个吗？

### ISSUE THREAD

**Issue by fandongtongxue** [yichengchen/ATV-Bilibili-demo#5]
如题

**Comment by yichengchen** [comment]
期待一个重写uicollectionflowlayout来动态配置的mr

**Comment by fandongtongxue** [comment]
`func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        CGSize(width: floor((.screenW - 60 * 5 ) / 4), height: 300)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumLineSpacingForSectionAt section: Int) -> CGFloat {
        60
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, minimumInteritemSpacingForSectionAt section: Int) -> CGFloat {
        60
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, insetForSectionAt section: Int) -> UIEdgeInsets {
        UIEdgeInsets(top: 60, left: 60, bottom: 60, right: 60)
    }`

**Comment by fandongtongxue** [comment]
别动态配置了，写死四行就可以，三行有点浪费
![Simulator Screen Shot - Apple TV 4K (at 1080p) (2nd generation) - 2022-08-27 at 14 44 39](https://user-images.githubusercontent.com/21986591/187018556-aeecd5d1-3a4d-4aa8-959b-6514ced714ff.png)

**Comment by yichengchen** [comment]
已完成
