### ISSUE TITLE
Xcode-Beta 15编译报错

### ISSUE THREAD

**Issue by Hotinosin** [yichengchen/ATV-Bilibili-demo#75]
具体报错如下
![20230608-103846](https://github.com/yichengchen/ATV-Bilibili-demo/assets/87741985/6c255a34-5129-485c-8699-0330ed674e83)
想问下有什么解决方法吗，因为Xcode14太大，硬盘负担不下所以改用了xcode-beta15
感谢！

**Comment by yichengchen** [comment]
fixed
