### ISSUE TITLE
Failed to build 

### ISSUE THREAD

**Issue by Gerjarr** [yichengchen/ATV-Bilibili-demo#76]
Xcode 15.0 beta(15A5160n)

<img width="1005" alt="image" src="https://github.com/yichengchen/ATV-Bilibili-demo/assets/104193836/7a21b6ad-773f-49d1-a611-757aa9aa8f41">

**Comment by haowenwu** [comment]
fix at ffb748ccf1fb4d0c2c132eb889522870d50a90b0
