### ISSUE TITLE
疑似cookie被黑，从来没有被自动关注过机器人，我直接下的action最新的ipa文件，当前有什么问题吗？

### ISSUE THREAD

**Issue by Paul-Deng** [yichengchen/ATV-Bilibili-demo#81]
如题：不知道为什么自动关注了一批人，刚用这个几天。有什么排查手段吗？大约多关注了150人。
<img width="614" alt="image" src="https://github.com/yichengchen/ATV-Bilibili-demo/assets/29682349/5a5848fd-83a8-41a8-b60b-e91f4f5ddf17">

**Comment by yichengchen** [comment]
本项目没有发布任何tf，不能保证市面上公开的tf有任何私料。

目前我的账号看起来没什么异常，怀疑的点是当前项目里有些api没使用https，有被运营商偷token的可能性

**Comment by Paul-Deng** [comment]
> 本项目没有发布任何tf，不能保证市面上公开的tf有任何私料。
> 
> 目前我的账号看起来没什么异常，怀疑的点是当前项目里有些api没使用https，有被运营商偷token的可能性

好奇怪，就只是8.7号当天被自动关注了，在这段期间就扫过这一次码。后续就没有了。家里有台服务器挂了爱快网关，appletv的网络线路网关是openwrt的梯子插件，届时排查下。

**Comment by Paul-Deng** [comment]
我更倾向于我刷的openwrt固件有问题。我正常家里是走国内网，一直没出现问题。但是走梯子网络扫次码就出现这个现象了。尴尬。

**Comment by yichengchen** [comment]
🤔 https://x.com/tualatrix/status/1693810999927931315
