### ISSUE TITLE
搜索用iPhone输入文字后，会有几率闪退

### ISSUE THREAD

**Issue by ZsIsMe** [yichengchen/ATV-Bilibili-demo#83]
我在搜索页面进行2次差不多的搜索，”刃牙“，”刃牙刃牙“，”刃牙“
App就会崩溃。
Thread 1: "Diffable data source detected section identifiers that are equal but have different hash values. Two identifiers which compare as equal must return the same hash value. You must fix this in the Hashable (Swift) or hash property (Objective-C) implementation for the type of these identifiers. Identifiers that are equal but have different hash values: (BilibiliLive.SearchList(title: \"视频\", width: <NSCollectionLayoutDimension: 0x283c4ff20>, height: <NSCollectionLayoutDimension: 0x283c4ff60>, scrollingBehavior: __C.UICollectionLayoutSectionOrthogonalScrollingBehavior)) and (BilibiliLive.SearchList(title: \"视频\", width: <NSCollectionLayoutDimension: 0x283c7ac60>, height: <NSCollectionLayoutDimension: 0x283c79420>, scrollingBehavior: __C.UICollectionLayoutSectionOrthogonalScrollingBehavior))"

**Comment by ZsIsMe** [comment]
这个像是哈希键重复了

**Comment by haowenwu** [comment]
Fix at #85
