### ISSUE TITLE
Issue about subclassing AVPlayerViewController

### ISSUE THREAD

**Issue by Kyle-Ye** [yichengchen/ATV-Bilibili-demo#89]
The current VC inheritance chain is VideoPlayerViewController -> CommonPlayerViewController -> AVPlayerViewController.

But Apple's AVKit [documentation](https://developer.apple.com/documentation/avkit/avplayerviewcontroller) states that "The framework doesn’t support subclassing AVPlayerViewController."

> But AVKit is written by ObjectiveC, `AVPlayerViewController` can't marked as `final class` to stop us from inheriting it.

Some issue I met before([setting `AVPlaybackSpeed` and not working](https://github.com/yichengchen/ATV-Bilibili-demo/pull/86#issuecomment-1802126425)) may also be related to our usage of inheritance for AVPlayerViewController.

But anyway using subclass of `AVPlayerViewController` has some risk that it may not work in future OS update. I'd like to suggest we make `CommonPlayerViewController` a simple class or a subclass of NSObject and add a property `var player: AVPlayerViewController` to refactor our codebase.

**Comment by yichengchen** [comment]
Try with simply putting AVPlayerViewController as a child controller of CommonPlayerViewController (fix/avplayerVC-child). But the directional key of the remote is not working or not forwarded to  AVPlayerViewController. May need more research with the tvOS event chain.

**Comment by yichengchen** [comment]
another propose is make CommonPlayerViewController become a simple util to present avplayerVC only. move all danmuView, maskView and related logic to the overlayContentView of the AVPlayerVC.

**Comment by yichengchen** [comment]
If we just make CommonPlayerViewController a simple class or a subclass of NSObject and add a property var player: AVPlayerViewController. How to prevent the CommonPlayerViewController deinit immediately after present the  AVPlayerViewController. There is not a view hierarchy to keep it. Or just do some hacky work like the  overlayContentView holding the CommonPlayerViewController?

**Comment by Kyle-Ye** [comment]
> If we just make CommonPlayerViewController a simple class or a subclass of NSObject and add a property var player: AVPlayerViewController. How to prevent the CommonPlayerViewController deinit immediately after present the AVPlayerViewController. There is not a view hierarchy to keep it. Or just do some hacky work like the overlayContentView holding the CommonPlayerViewController?

Take VideoDetailViewController/VideoPlayerViewController as an example:

In `VideoDetailViewController`, we try to present if from a vc. And when `direatlyEnterVideo` is true and the present is complete, we'll continue to make `VideoDetailViewController` to present our `VideoPlayerViewController`

The original code:
```swift
func present(from vc: UIViewController, direatlyEnterVideo: Bool = Settings.direatlyEnterVideo) {
    if !direatlyEnterVideo {
        vc.present(self, animated: true)
    } else {
        vc.present(self, animated: false) { [weak self] in
            guard let self else { return }
            let player = VideoPlayerViewController(playInfo: PlayInfo(aid: self.aid, cid: self.cid, epid: self.epid, isBangumi: self.isBangumi))
            self.present(player, animated: true)
        }
    }
}
```

The new code can be written as follow
1. In the init method of `VideoPlayerViewController/CommonPlayerViewController`, we create a `AVPlayerViewController ` and store it as an unowned(**not weak**) reference. Also we somehow make `AVPlayerViewController` strongly hold our `VideoPlayerViewController/CommonPlayerViewController` instance.

```swift
func present(from vc: UIViewController, direatlyEnterVideo: Bool = Settings.direatlyEnterVideo) {
    if !direatlyEnterVideo {
        vc.present(self, animated: true)
    } else {
        vc.present(self, animated: false) { [weak self] in
            guard let self else { return }
            let controller = VideoPlayerViewController(playInfo: PlayInfo(aid: self.aid, cid: self.cid, epid: self.epid, isBangumi: self.isBangumi))
            self.present(controller.player, animated: true)
        }
    }
}
```

**Comment by yichengchen** [comment]
yep, I am thinking is there is a simply elegant way to make `AVPlayerViewController` strongly hold our `VideoPlayerViewController/CommonPlayerViewController` instance without subclassing. Like use the `AVPlayerViewController.overlayContentView` to hold the controller, but it's a little strange.

**Comment by yichengchen** [comment]
After override the `preferredFocusEnvironments` of the `CommonPlayerViewController`, the directional key of the remote works. Maybe we can still put the `AVPlayerViewController ` as the subclass of the `CommonPlayerViewController `.

**Comment by Kyle-Ye** [comment]
> After override the `preferredFocusEnvironments` of the `CommonPlayerViewController`, the directional key of the remote works. Maybe we can still put the `AVPlayerViewController ` as the subclass of the `CommonPlayerViewController `.

Typo here? I guess you mean putting AVPlayerViewController as a child controller of CommonPlayerViewController

**Comment by Kyle-Ye** [comment]
Awesome work. I'll give it try later this day to confirm this is fixed as expected.
