### ISSUE TITLE
请问一下AnimeOne/Anime1

### ISSUE THREAD

**Issue by felix0324324** [yichengchen/ATV-Bilibili-demo#92]
之前有见过在"登出"按钮附近有出现过
AnimeOne/Anime1 然后里面的动画都可以看到的
请问这要怎样重现?? (tvos洗机后就消失了...

**Comment by felix0324324** [comment]
![image](https://github.com/yichengchen/ATV-Bilibili-demo/assets/16462532/584540a1-9214-4175-b7f1-9e87665c979a)

**Comment by felix0324324** [comment]
看了以前的code的確存在
已經魔改好自用了，謝謝你

**Comment by yichengchen** [comment]
这个现在已经不能用了吧？所以才移除的
