### ISSUE TITLE
视频详情中合集显示异常

### ISSUE THREAD

**Issue by higuaifan** [yichengchen/ATV-Bilibili-demo#96]
# 问题

比如说`马刀刻森`的`合集`：`马刀西游`中：
在项目中显示如下：
<img width="1927" alt="image" src="https://github.com/yichengchen/ATV-Bilibili-demo/assets/9988024/70214c2b-3d62-4870-8090-e38f7676e152">
合集中显示的内容是所有`马刀剧场`的内容。
即[这段代码](https://github.com/yichengchen/ATV-Bilibili-demo/blob/c9c215fb9ce9b9329bc751a157546a9cde850d6a/BilibiliLive/Component/Video/VideoDetailViewController.swift#L328C1-L330C10)：
``` swift
        if allUgcEpisodes.count > 0 {
            ugcCollectionView.scrollToItem(at: IndexPath(item: allUgcEpisodes.map { $0.aid }.firstIndex(of: aid) ?? 0, section: 0), at: .left, animated: false)
        }
```
整合了所有的`ugc_season.sections`内容。

而实际上`bilibili`中显示：
![image](https://github.com/yichengchen/ATV-Bilibili-demo/assets/9988024/adbdeaf3-f106-4df2-b30e-bd8ddb83fa1d)
看起来好像`bilibili`中合集包含了子合集，
![image](https://github.com/yichengchen/ATV-Bilibili-demo/assets/9988024/5174680b-8fe3-4e44-9822-6da2a09f1780)

这里是[视频链接](https://www.bilibili.com/video/BV1Jm411X7D3)

但是如果说是`半佛`的合集：
![image](https://github.com/yichengchen/ATV-Bilibili-demo/assets/9988024/4cc677cc-9336-4beb-a7a3-653d9ef7d072)

是没有问题的。

# 预期解决方案

`马刀刻森`例子的[API](https://api.bilibili.com/x/web-interface/view/detail?aid=1900494962)获得的`ugc_season`数据结构如下差不多是这样的：
![image](https://github.com/yichengchen/ATV-Bilibili-demo/assets/9988024/ea340aca-fb1e-459b-b9ee-d72778640e05)

如果仔细对照的话，`episodes`中的数据似乎不是严格按照创建时间排列的，并且`title`有滞后性。

我本地`查找了一下合集，并进行了一个时间上的排序，替换了下标题`，稍微消耗一点算力但是获得了正确的信息。

我想问下合集目前的显示方式是有意为之还是因为`Bilibili API`的迭代造成了一些异常?

如果需要迭代的话，我可以提交`PR`进行迭代吗？

-------------

另外，连续播放上好像也有点问题，需要新开一个`issue`讨论吗？

**Comment by yichengchen** [comment]
目前的合集显示方式（直接合并）是因为没有响应的ui设计，可以尽情pr~

**Comment by yichengchen** [comment]
或者说每个合集用1行显示？那会不会占据太多行

**Comment by higuaifan** [comment]
> 或者说每个合集用1行显示？那会不会占据太多行

每个合集一行感觉是有点多了，要优雅完整的话，可能得调整UI，
不过像马刀这种稍微有点复杂的合集我碰到的也就他一个，
回头先整个demo版本试试看🐶

**Comment by higuaifan** [comment]
@yichengchen 
坏了，有没有碰到过调试时视频卡住不播放的情况，不是`swift`熟练工的不太知道该怎么解决。
类似于这样：
<img width="344" alt="image" src="https://github.com/yichengchen/ATV-Bilibili-demo/assets/9988024/65490972-d89b-468d-a2a5-1feae6a758bf">
