### ISSUE TITLE
直播流crash

### ISSUE THREAD

**Issue by uestcwangci** [yichengchen/ATV-Bilibili-demo#97]
最近看直播流，发现到一定时间，大概30min-60min，程序会异常退出，用的c9c215fb9ce9b9329bc751a157546a9cde850d6a这次编译的版本，以前好像没遇到过

**Comment by yichengchen** [comment]
能不能用Xcode收集一下crash log？

**Comment by yichengchen** [comment]
用最新版试试，解决了部分内存泄漏

**Comment by uestcwangci** [comment]
👍给力
